[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "KnowledgeWarehouse"
authors = [{name = "payne wu", email = "wuzhipeng1289690157@gmail.com"}]
dynamic = ["version", "description"]
